var searchData=
[
  ['fill',['Fill',['../class_grid_queue.html#a3d9aab1c0581d48c2e8fa93c8d6f3bb9',1,'GridQueue']]],
  ['fillandresetdrain',['FillAndResetDrain',['../class_grid_queue.html#a19c665812faddb2c26b059080cde31b3',1,'GridQueue']]],
  ['fillsize',['FillSize',['../class_grid_queue.html#a1152b7d294c577a69cf754b2f75f4746',1,'GridQueue']]],
  ['flagged',['Flagged',['../struct_device_partition.html#a0c1ee31b8e79669a9e820a2ed103f181',1,'DevicePartition::Flagged()'],['../struct_device_select.html#a1b5d9f20bb019a499cf415fb536ff87a',1,'DeviceSelect::Flagged()']]],
  ['flagheads',['FlagHeads',['../class_block_adjacent_difference.html#acbc572b3752666dce68b010113d0fa4c',1,'BlockAdjacentDifference::FlagHeads(FlagT(&amp;output)[ITEMS_PER_THREAD], T(&amp;input)[ITEMS_PER_THREAD], FlagOp flag_op)'],['../class_block_adjacent_difference.html#acb830a171aaa3125803551dcc8040b09',1,'BlockAdjacentDifference::FlagHeads(FlagT(&amp;output)[ITEMS_PER_THREAD], T(&amp;input)[ITEMS_PER_THREAD], FlagOp flag_op, T tile_predecessor_item)'],['../class_block_discontinuity.html#a98660a8a3ca5397b2fbf8da0a450ca24',1,'BlockDiscontinuity::FlagHeads(FlagT(&amp;head_flags)[ITEMS_PER_THREAD], T(&amp;input)[ITEMS_PER_THREAD], FlagOp flag_op)'],['../class_block_discontinuity.html#aa1714ddccf5967e1eb0bb070f8a05041',1,'BlockDiscontinuity::FlagHeads(FlagT(&amp;head_flags)[ITEMS_PER_THREAD], T(&amp;input)[ITEMS_PER_THREAD], FlagOp flag_op, T tile_predecessor_item)']]],
  ['flagheadsandtails',['FlagHeadsAndTails',['../class_block_adjacent_difference.html#a55c5a5b9f4125035a7c0d9bc21324639',1,'BlockAdjacentDifference::FlagHeadsAndTails(FlagT(&amp;head_flags)[ITEMS_PER_THREAD], FlagT(&amp;tail_flags)[ITEMS_PER_THREAD], T(&amp;input)[ITEMS_PER_THREAD], FlagOp flag_op)'],['../class_block_adjacent_difference.html#a01302dc02b6f1ab6106c6c24d7010620',1,'BlockAdjacentDifference::FlagHeadsAndTails(FlagT(&amp;head_flags)[ITEMS_PER_THREAD], FlagT(&amp;tail_flags)[ITEMS_PER_THREAD], T tile_successor_item, T(&amp;input)[ITEMS_PER_THREAD], FlagOp flag_op)'],['../class_block_adjacent_difference.html#a0383853c73cb265a961b3d3df1272360',1,'BlockAdjacentDifference::FlagHeadsAndTails(FlagT(&amp;head_flags)[ITEMS_PER_THREAD], T tile_predecessor_item, FlagT(&amp;tail_flags)[ITEMS_PER_THREAD], T(&amp;input)[ITEMS_PER_THREAD], FlagOp flag_op)'],['../class_block_adjacent_difference.html#a8e01d5dc95d07261fd951bdc56803790',1,'BlockAdjacentDifference::FlagHeadsAndTails(FlagT(&amp;head_flags)[ITEMS_PER_THREAD], T tile_predecessor_item, FlagT(&amp;tail_flags)[ITEMS_PER_THREAD], T tile_successor_item, T(&amp;input)[ITEMS_PER_THREAD], FlagOp flag_op)'],['../class_block_discontinuity.html#a91204c33be69fc2b66407be9ffd2b3fb',1,'BlockDiscontinuity::FlagHeadsAndTails(FlagT(&amp;head_flags)[ITEMS_PER_THREAD], FlagT(&amp;tail_flags)[ITEMS_PER_THREAD], T(&amp;input)[ITEMS_PER_THREAD], FlagOp flag_op)'],['../class_block_discontinuity.html#a115fe957d5c97a6f31875f82ba8c2211',1,'BlockDiscontinuity::FlagHeadsAndTails(FlagT(&amp;head_flags)[ITEMS_PER_THREAD], FlagT(&amp;tail_flags)[ITEMS_PER_THREAD], T tile_successor_item, T(&amp;input)[ITEMS_PER_THREAD], FlagOp flag_op)'],['../class_block_discontinuity.html#a75c3f77926650f059e316522e8e92c47',1,'BlockDiscontinuity::FlagHeadsAndTails(FlagT(&amp;head_flags)[ITEMS_PER_THREAD], T tile_predecessor_item, FlagT(&amp;tail_flags)[ITEMS_PER_THREAD], T(&amp;input)[ITEMS_PER_THREAD], FlagOp flag_op)'],['../class_block_discontinuity.html#a97ac4465ad7c0ec09aba70f5df374abd',1,'BlockDiscontinuity::FlagHeadsAndTails(FlagT(&amp;head_flags)[ITEMS_PER_THREAD], T tile_predecessor_item, FlagT(&amp;tail_flags)[ITEMS_PER_THREAD], T tile_successor_item, T(&amp;input)[ITEMS_PER_THREAD], FlagOp flag_op)']]],
  ['flagtails',['FlagTails',['../class_block_adjacent_difference.html#a30900de7e348f3ac8f12e987c31e86e2',1,'BlockAdjacentDifference::FlagTails(FlagT(&amp;output)[ITEMS_PER_THREAD], T(&amp;input)[ITEMS_PER_THREAD], FlagOp flag_op)'],['../class_block_adjacent_difference.html#a16304bd4f9a1ef5cfbbe0d5babcdd2f8',1,'BlockAdjacentDifference::FlagTails(FlagT(&amp;output)[ITEMS_PER_THREAD], T(&amp;input)[ITEMS_PER_THREAD], FlagOp flag_op, T tile_successor_item)'],['../class_block_discontinuity.html#a1fa21ab58b4675c5dce9b3048935dfbc',1,'BlockDiscontinuity::FlagTails(FlagT(&amp;tail_flags)[ITEMS_PER_THREAD], T(&amp;input)[ITEMS_PER_THREAD], FlagOp flag_op)'],['../class_block_discontinuity.html#aa3848de04ee63bd63e1f69301094322b',1,'BlockDiscontinuity::FlagTails(FlagT(&amp;tail_flags)[ITEMS_PER_THREAD], T(&amp;input)[ITEMS_PER_THREAD], FlagOp flag_op, T tile_successor_item)']]],
  ['freeallcached',['FreeAllCached',['../struct_caching_device_allocator.html#af10c1b2d44dbf5b51e6504731e5384e6',1,'CachingDeviceAllocator']]],
  ['fancy_20iterators',['Fancy iterators',['../group___util_iterator.html',1,'']]]
];
