var searchData=
[
  ['debug',['Debug',['../group___util_mgmt.html#ga82bd0265beca751b05b669677995471a',1,'util_debug.cuh']]],
  ['deprecated_20list',['Deprecated List',['../deprecated.html',1,'']]],
  ['device_5fhistogram_2ecuh',['device_histogram.cuh',['../device__histogram_8cuh.html',1,'']]],
  ['device_5fpartition_2ecuh',['device_partition.cuh',['../device__partition_8cuh.html',1,'']]],
  ['device_5fradix_5fsort_2ecuh',['device_radix_sort.cuh',['../device__radix__sort_8cuh.html',1,'']]],
  ['device_5freduce_2ecuh',['device_reduce.cuh',['../device__reduce_8cuh.html',1,'']]],
  ['device_5frun_5flength_5fencode_2ecuh',['device_run_length_encode.cuh',['../device__run__length__encode_8cuh.html',1,'']]],
  ['device_5fscan_2ecuh',['device_scan.cuh',['../device__scan_8cuh.html',1,'']]],
  ['device_5fsegmented_5fradix_5fsort_2ecuh',['device_segmented_radix_sort.cuh',['../device__segmented__radix__sort_8cuh.html',1,'']]],
  ['device_5fsegmented_5freduce_2ecuh',['device_segmented_reduce.cuh',['../device__segmented__reduce_8cuh.html',1,'']]],
  ['device_5fsegmented_5fsort_2ecuh',['device_segmented_sort.cuh',['../device__segmented__sort_8cuh.html',1,'']]],
  ['device_5fselect_2ecuh',['device_select.cuh',['../device__select_8cuh.html',1,'']]],
  ['device_5fspmv_2ecuh',['device_spmv.cuh',['../device__spmv_8cuh.html',1,'']]],
  ['deviceadjacentdifference',['DeviceAdjacentDifference',['../struct_device_adjacent_difference.html',1,'']]],
  ['deviceallocate',['DeviceAllocate',['../struct_caching_device_allocator.html#a17428b378d89ca12215616239e69d67f',1,'CachingDeviceAllocator::DeviceAllocate(int device, void **d_ptr, size_t bytes, cudaStream_t active_stream=0)'],['../struct_caching_device_allocator.html#adc2b7a714765a6aee7081fe285bf88b1',1,'CachingDeviceAllocator::DeviceAllocate(void **d_ptr, size_t bytes, cudaStream_t active_stream=0)']]],
  ['devicecount',['DeviceCount',['../group___util_mgmt.html#ga3b14be921c2e1331bc5ec2fa7bb8781e',1,'util_device.cuh']]],
  ['devicecountuncached',['DeviceCountUncached',['../group___util_mgmt.html#ga7e6e03291175631642882767e3153527',1,'util_device.cuh']]],
  ['devicefree',['DeviceFree',['../struct_caching_device_allocator.html#a4d28109397b125fada8bf28f0df83c59',1,'CachingDeviceAllocator::DeviceFree(int device, void *d_ptr)'],['../struct_caching_device_allocator.html#a2ffa06fb8b1dfc248d8efb1816d9b32e',1,'CachingDeviceAllocator::DeviceFree(void *d_ptr)']]],
  ['devicehistogram',['DeviceHistogram',['../struct_device_histogram.html',1,'']]],
  ['devicemergesort',['DeviceMergeSort',['../struct_device_merge_sort.html',1,'']]],
  ['device_2dwide_20primitives',['Device-wide primitives',['../group___device_module.html',1,'']]],
  ['devicepartition',['DevicePartition',['../struct_device_partition.html',1,'']]],
  ['deviceradixsort',['DeviceRadixSort',['../struct_device_radix_sort.html',1,'']]],
  ['devicereduce',['DeviceReduce',['../struct_device_reduce.html',1,'']]],
  ['devicerunlengthencode',['DeviceRunLengthEncode',['../struct_device_run_length_encode.html',1,'']]],
  ['devicescan',['DeviceScan',['../struct_device_scan.html',1,'']]],
  ['devicesegmentedradixsort',['DeviceSegmentedRadixSort',['../struct_device_segmented_radix_sort.html',1,'']]],
  ['devicesegmentedreduce',['DeviceSegmentedReduce',['../struct_device_segmented_reduce.html',1,'']]],
  ['devicesegmentedsort',['DeviceSegmentedSort',['../struct_device_segmented_sort.html',1,'']]],
  ['deviceselect',['DeviceSelect',['../struct_device_select.html',1,'']]],
  ['devicespmv',['DeviceSpmv',['../struct_device_spmv.html',1,'']]],
  ['difference',['Difference',['../struct_difference.html',1,'']]],
  ['difference_5ftype',['difference_type',['../class_arg_index_input_iterator.html#aea671cc79d15976b907db1a460d0283d',1,'ArgIndexInputIterator::difference_type()'],['../class_cache_modified_input_iterator.html#ab34256127c86b6ff96097004a76c4fc9',1,'CacheModifiedInputIterator::difference_type()'],['../class_cache_modified_output_iterator.html#a920d178562a6b6ada394a03cbb72fbf0',1,'CacheModifiedOutputIterator::difference_type()'],['../class_constant_input_iterator.html#a07fe0ceab3c41bfef8ac7ab0df115379',1,'ConstantInputIterator::difference_type()'],['../class_counting_input_iterator.html#a8f6001b40ba4f40556b3255e40a8ee1e',1,'CountingInputIterator::difference_type()'],['../class_discard_output_iterator.html#a9416623f150e446e8f9dc5ec74f0a4aa',1,'DiscardOutputIterator::difference_type()'],['../class_tex_obj_input_iterator.html#aaea3513dfb4b56bb03bcfa446adef638',1,'TexObjInputIterator::difference_type()'],['../class_tex_ref_input_iterator.html#aea1b3a8ba65ab6e4418731cea74551fe',1,'TexRefInputIterator::difference_type()'],['../class_transform_input_iterator.html#a9a269f870fa37853361771ac6c2aac94',1,'TransformInputIterator::difference_type()']]],
  ['discard_5foutput_5fiterator_2ecuh',['discard_output_iterator.cuh',['../discard__output__iterator_8cuh.html',1,'']]],
  ['discardoutputiterator',['DiscardOutputIterator',['../class_discard_output_iterator.html',1,'DiscardOutputIterator&lt; OffsetT &gt;'],['../class_discard_output_iterator.html#a542367fac0932d27a5141a8b2b103bf4',1,'DiscardOutputIterator::DiscardOutputIterator()']]],
  ['dispatchinit',['DispatchInit',['../struct_grid_even_share.html#a86d32e154ba88074ae57ddc575a6886e',1,'GridEvenShare']]],
  ['division',['Division',['../struct_division.html',1,'']]],
  ['down',['Down',['../class_block_shuffle.html#a2e04b1a948feaeabbbc3c6da14c2258d',1,'BlockShuffle::Down(T(&amp;input)[ITEMS_PER_THREAD], T(&amp;prev)[ITEMS_PER_THREAD])'],['../class_block_shuffle.html#a0c3812a8bd3dd7adb9bce04949261a80',1,'BlockShuffle::Down(T(&amp;input)[ITEMS_PER_THREAD], T(&amp;prev)[ITEMS_PER_THREAD], T &amp;block_prefix)']]],
  ['drain',['Drain',['../class_grid_queue.html#a3a4fb15c63d4449902cf6362f6616f42',1,'GridQueue']]],
  ['device_2c_20kernel_2c_20and_20storage_20management',['Device, kernel, and storage management',['../group___util_mgmt.html',1,'']]]
];
