var searchData=
[
  ['debug',['Debug',['../group___util_mgmt.html#ga5a175d2a88f63f7f1ab30e8b4f2cfa95',1,'cub']]],
  ['deprecated_20list',['Deprecated List',['../deprecated.html',1,'']]],
  ['device_5fhistogram_2ecuh',['device_histogram.cuh',['../device__histogram_8cuh.html',1,'']]],
  ['device_5fpartition_2ecuh',['device_partition.cuh',['../device__partition_8cuh.html',1,'']]],
  ['device_5fradix_5fsort_2ecuh',['device_radix_sort.cuh',['../device__radix__sort_8cuh.html',1,'']]],
  ['device_5freduce_2ecuh',['device_reduce.cuh',['../device__reduce_8cuh.html',1,'']]],
  ['device_5frun_5flength_5fencode_2ecuh',['device_run_length_encode.cuh',['../device__run__length__encode_8cuh.html',1,'']]],
  ['device_5fscan_2ecuh',['device_scan.cuh',['../device__scan_8cuh.html',1,'']]],
  ['device_5fsegmented_5fradix_5fsort_2ecuh',['device_segmented_radix_sort.cuh',['../device__segmented__radix__sort_8cuh.html',1,'']]],
  ['device_5fsegmented_5freduce_2ecuh',['device_segmented_reduce.cuh',['../device__segmented__reduce_8cuh.html',1,'']]],
  ['device_5fsegmented_5fsort_2ecuh',['device_segmented_sort.cuh',['../device__segmented__sort_8cuh.html',1,'']]],
  ['device_5fselect_2ecuh',['device_select.cuh',['../device__select_8cuh.html',1,'']]],
  ['device_5fspmv_2ecuh',['device_spmv.cuh',['../device__spmv_8cuh.html',1,'']]],
  ['deviceadjacentdifference',['DeviceAdjacentDifference',['../structcub_1_1_device_adjacent_difference.html',1,'cub']]],
  ['deviceallocate',['DeviceAllocate',['../structcub_1_1_caching_device_allocator.html#ae1088ac6ba6e5d55832ffbc0b2a5d714',1,'cub::CachingDeviceAllocator::DeviceAllocate(int device, void **d_ptr, size_t bytes, cudaStream_t active_stream=0)'],['../structcub_1_1_caching_device_allocator.html#ab2fe4020cf8bc86ad886c797525ac8ea',1,'cub::CachingDeviceAllocator::DeviceAllocate(void **d_ptr, size_t bytes, cudaStream_t active_stream=0)']]],
  ['devicecount',['DeviceCount',['../group___util_mgmt.html#gae60e74dc4a3e97efb70b775e5e430496',1,'cub']]],
  ['devicecountuncached',['DeviceCountUncached',['../group___util_mgmt.html#ga226afbb6eb3c475ddbc6f5614aca5363',1,'cub']]],
  ['devicefree',['DeviceFree',['../structcub_1_1_caching_device_allocator.html#a66e72cc3cc7d0dbd59148ac7c4ba0de6',1,'cub::CachingDeviceAllocator::DeviceFree(int device, void *d_ptr)'],['../structcub_1_1_caching_device_allocator.html#adbf65c59172b140420636e150325deeb',1,'cub::CachingDeviceAllocator::DeviceFree(void *d_ptr)']]],
  ['devicehistogram',['DeviceHistogram',['../structcub_1_1_device_histogram.html',1,'cub']]],
  ['devicemergesort',['DeviceMergeSort',['../structcub_1_1_device_merge_sort.html',1,'cub']]],
  ['device_2dwide_20primitives',['Device-wide primitives',['../group___device_module.html',1,'']]],
  ['devicepartition',['DevicePartition',['../structcub_1_1_device_partition.html',1,'cub']]],
  ['deviceradixsort',['DeviceRadixSort',['../structcub_1_1_device_radix_sort.html',1,'cub']]],
  ['devicereduce',['DeviceReduce',['../structcub_1_1_device_reduce.html',1,'cub']]],
  ['devicerunlengthencode',['DeviceRunLengthEncode',['../structcub_1_1_device_run_length_encode.html',1,'cub']]],
  ['devicescan',['DeviceScan',['../structcub_1_1_device_scan.html',1,'cub']]],
  ['devicesegmentedradixsort',['DeviceSegmentedRadixSort',['../structcub_1_1_device_segmented_radix_sort.html',1,'cub']]],
  ['devicesegmentedreduce',['DeviceSegmentedReduce',['../structcub_1_1_device_segmented_reduce.html',1,'cub']]],
  ['devicesegmentedsort',['DeviceSegmentedSort',['../struct_device_segmented_sort.html',1,'']]],
  ['deviceselect',['DeviceSelect',['../structcub_1_1_device_select.html',1,'cub']]],
  ['devicespmv',['DeviceSpmv',['../structcub_1_1_device_spmv.html',1,'cub']]],
  ['difference',['Difference',['../structcub_1_1_difference.html',1,'cub']]],
  ['difference_5ftype',['difference_type',['../classcub_1_1_arg_index_input_iterator.html#aa5baa6e0a4526a1a73b38632838e947d',1,'cub::ArgIndexInputIterator::difference_type()'],['../classcub_1_1_cache_modified_input_iterator.html#a268f1e7a4b42a05c5b4d0bca2775c26e',1,'cub::CacheModifiedInputIterator::difference_type()'],['../classcub_1_1_cache_modified_output_iterator.html#ac8cdd3a29db7e398f14e44a7aa054750',1,'cub::CacheModifiedOutputIterator::difference_type()'],['../classcub_1_1_constant_input_iterator.html#ab45cc48afbfda7eaa3b4ea643e719c33',1,'cub::ConstantInputIterator::difference_type()'],['../classcub_1_1_counting_input_iterator.html#ac66dea2a687f0ad6ed0cbcd6217a3029',1,'cub::CountingInputIterator::difference_type()'],['../classcub_1_1_discard_output_iterator.html#a502bc5d0752a9b85b134fd1d00ba5057',1,'cub::DiscardOutputIterator::difference_type()'],['../classcub_1_1_tex_obj_input_iterator.html#a710012acbff3dd0c35822951e28148ea',1,'cub::TexObjInputIterator::difference_type()'],['../classcub_1_1_tex_ref_input_iterator.html#aff1afce146f69adb655e2ff7366b869f',1,'cub::TexRefInputIterator::difference_type()'],['../classcub_1_1_transform_input_iterator.html#ac05064e9ad33dc032452e3d09e8768f6',1,'cub::TransformInputIterator::difference_type()']]],
  ['discard_5foutput_5fiterator_2ecuh',['discard_output_iterator.cuh',['../discard__output__iterator_8cuh.html',1,'']]],
  ['discardoutputiterator',['DiscardOutputIterator',['../classcub_1_1_discard_output_iterator.html#ab43f12bf97b18ca58735286a64740c2e',1,'cub::DiscardOutputIterator']]],
  ['discardoutputiterator',['DiscardOutputIterator',['../classcub_1_1_discard_output_iterator.html',1,'cub']]],
  ['dispatchinit',['DispatchInit',['../structcub_1_1_grid_even_share.html#a7499a58124758b950bb43e67c5660b11',1,'cub::GridEvenShare']]],
  ['division',['Division',['../structcub_1_1_division.html',1,'cub']]],
  ['down',['Down',['../classcub_1_1_block_shuffle.html#a32b61b3c3230f122bbcb363d80aafbd5',1,'cub::BlockShuffle::Down(T(&amp;input)[ITEMS_PER_THREAD], T(&amp;prev)[ITEMS_PER_THREAD])'],['../classcub_1_1_block_shuffle.html#a7b8d89532ca483e141732f2889454ea2',1,'cub::BlockShuffle::Down(T(&amp;input)[ITEMS_PER_THREAD], T(&amp;prev)[ITEMS_PER_THREAD], T &amp;block_prefix)']]],
  ['download_20cub_21',['Download CUB!',['../download_cub.html',1,'']]],
  ['drain',['Drain',['../classcub_1_1_grid_queue.html#aa5a596bb3c8e9b8cdc049e7a8d061973',1,'cub::GridQueue']]],
  ['device_2c_20kernel_2c_20and_20storage_20management',['Device, kernel, and storage management',['../group___util_mgmt.html',1,'']]]
];
