var searchData=
[
  ['matchany',['MatchAny',['../util__ptx_8cuh.html#a7a8dd620271651676c81a4a5a2196345',1,'util_ptx.cuh']]],
  ['max',['Max',['../struct_device_reduce.html#a30ab16308ebfccdebff82a90ac5dfe66',1,'DeviceReduce::Max()'],['../struct_device_segmented_reduce.html#aaa09df63e53d717342fdf1d09cc58651',1,'DeviceSegmentedReduce::Max()']]],
  ['maxsmoccupancy',['MaxSmOccupancy',['../group___util_mgmt.html#ga63b9b6c566ac4bf39e9fe8ed51daeeb1',1,'util_device.cuh']]],
  ['min',['Min',['../struct_device_reduce.html#ae77981dd1db6263e3d51c8d88ea38972',1,'DeviceReduce::Min()'],['../struct_device_segmented_reduce.html#aff72e3bab4987784f7faff5070d8bae8',1,'DeviceSegmentedReduce::Min()']]],
  ['multihistogrameven',['MultiHistogramEven',['../struct_device_histogram.html#adc92bf7af95bde4d319fa0cff66fdafd',1,'DeviceHistogram::MultiHistogramEven(void *d_temp_storage, size_t &amp;temp_storage_bytes, SampleIteratorT d_samples, CounterT *d_histogram[NUM_ACTIVE_CHANNELS], int num_levels[NUM_ACTIVE_CHANNELS], LevelT lower_level[NUM_ACTIVE_CHANNELS], LevelT upper_level[NUM_ACTIVE_CHANNELS], OffsetT num_pixels, cudaStream_t stream=0, bool debug_synchronous=false)'],['../struct_device_histogram.html#a6db1f402869205a822de3cb338258163',1,'DeviceHistogram::MultiHistogramEven(void *d_temp_storage, size_t &amp;temp_storage_bytes, SampleIteratorT d_samples, CounterT *d_histogram[NUM_ACTIVE_CHANNELS], int num_levels[NUM_ACTIVE_CHANNELS], LevelT lower_level[NUM_ACTIVE_CHANNELS], LevelT upper_level[NUM_ACTIVE_CHANNELS], OffsetT num_row_pixels, OffsetT num_rows, size_t row_stride_bytes, cudaStream_t stream=0, bool debug_synchronous=false)']]],
  ['multihistogramrange',['MultiHistogramRange',['../struct_device_histogram.html#ae91b82513e6a90c56ad03f85fad1a9e5',1,'DeviceHistogram::MultiHistogramRange(void *d_temp_storage, size_t &amp;temp_storage_bytes, SampleIteratorT d_samples, CounterT *d_histogram[NUM_ACTIVE_CHANNELS], int num_levels[NUM_ACTIVE_CHANNELS], LevelT *d_levels[NUM_ACTIVE_CHANNELS], OffsetT num_pixels, cudaStream_t stream=0, bool debug_synchronous=false)'],['../struct_device_histogram.html#ae0c83d56ea30ac8ece04a7fb457cfcde',1,'DeviceHistogram::MultiHistogramRange(void *d_temp_storage, size_t &amp;temp_storage_bytes, SampleIteratorT d_samples, CounterT *d_histogram[NUM_ACTIVE_CHANNELS], int num_levels[NUM_ACTIVE_CHANNELS], LevelT *d_levels[NUM_ACTIVE_CHANNELS], OffsetT num_row_pixels, OffsetT num_rows, size_t row_stride_bytes, cudaStream_t stream=0, bool debug_synchronous=false)']]]
];
